import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ConfigProvider, App } from "antd";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: "#0c0f12",
          },
        }}
      >
        <body className={inter.className}>
          <App>{children}</App>
        </body>
      </ConfigProvider>
    </html>
  );
}
